# SPDX-License-Identifier: BSD-3-Clause
LOCAL_DIR := $(GET_LOCAL_DIR)


QCDTBS += \
	  $(LOCAL_DIR)/hack2.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8260.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8660.dtb \
	 $(LOCAL_DIR)/QCOM_ID_APQ8060.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8960.dtb \
	 $(LOCAL_DIR)/QCOM_ID_APQ8064.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8930.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8630.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8230.dtb \
	 $(LOCAL_DIR)/QCOM_ID_APQ8030.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8627.dtb \
	 $(LOCAL_DIR)/QCOM_ID_MSM8227.dtb \
